- name: "playbook test"
  hosts: target
  tasks:
          - name: creates_file
            command: touch test.txt chdir=~


- name: "test adding line"
  hosts: target_host
  tasks:
          - lineinfile:
                  path: ~/test.txt
                  line: 'Hey you did it'
